<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\ImageLink;
use App\Models\OfferProduct;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //? --> Normal Products

        // Create products
        $products = [
            [
                'name' => 'بن الحموي كلاسيك مع هال',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات مختارة لأفضل تجربة شرب.',
                'category' => 'القهوة والشاي',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'شاي كامبو كلاسيك',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات مختارة لأفضل تجربة شرب.',
                'category' => 'القهوة والشاي',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'بيتيفور',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'كوكيز',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'كيك فهدة',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'كيكة',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'برازق السلطان',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'بسكويت أليتا',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'بسكويت بريك بارز',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'بسكويت رولانا',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'بسكويت ليفيل',
                'price' => 1000,
                'off' => 900,
                'about' => 'أشهى الحلويات للمناسبات الخاصة واليومية.',
                'category' => 'الحلويات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'تونا توليدو',
                'price' => 1000,
                'off' => 900,
                'about' => 'جودة عالية وطعم لا يقاوم.',
                'category' => 'المعلبات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'حمص مسلوق الشيف نديم',
                'price' => 1000,
                'off' => 900,
                'about' => 'جودة عالية وطعم لا يقاوم.',
                'category' => 'المعلبات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'جبنة سبرينغ بالقشطة',
                'price' => 1000,
                'off' => 900,
                'about' => 'طعم الطبيعة في كل قطعة.',
                'category' => 'الألبان والأجبان',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'جبنة نيو بارك',
                'price' => 1000,
                'off' => 900,
                'about' => 'طعم الطبيعة في كل قطعة.',
                'category' => 'الألبان والأجبان',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'جنبة أصابع',
                'price' => 1000,
                'off' => 900,
                'about' => 'طعم الطبيعة في كل قطعة.',
                'category' => 'الألبان والأجبان',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'حليب هوا الشام 1 ليتر',
                'price' => 1000,
                'off' => 900,
                'about' => 'طعم الطبيعة في كل قطعة.',
                'category' => 'الألبان والأجبان',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'لانشون الدرة دجاج',
                'price' => 1000,
                'off' => 900,
                'about' => 'طعم الطبيعة في كل قطعة.',
                'category' => 'الألبان والأجبان',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'جوز غير مقشر',
                'price' => 1000,
                'off' => 900,
                'about' => 'مكسرات محمصة بعناية لضمان أفضل طعم.',
                'category' => 'المحمصة',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'فستق عزبدة',
                'price' => 1000,
                'off' => 900,
                'about' => 'مكسرات محمصة بعناية لضمان أفضل طعم.',
                'category' => 'المحمصة',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خاطة اسكالوب الدجاج من الدرة',
                'price' => 1000,
                'off' => 900,
                'about' => 'لحوم طازجة ومختارة بعناية.',
                'category' => 'اللحوم',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'صدر دجاج',
                'price' => 1000,
                'off' => 900,
                'about' => 'لحوم طازجة ومختارة بعناية.',
                'category' => 'اللحوم',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'شاورما دجاج',
                'price' => 1000,
                'off' => 900,
                'about' => 'لحوم طازجة ومختارة بعناية.',
                'category' => 'اللحوم',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'لحم بقر',
                'price' => 1000,
                'off' => 900,
                'about' => 'لحوم طازجة ومختارة بعناية.',
                'category' => 'اللحوم',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خبز سياحي شمسين',
                'price' => 1000,
                'off' => 900,
                'about' => 'خبز يومي طازج ومعجنات شهية.',
                'category' => 'الخبز والمعجنات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خبز شعير تنور زمان',
                'price' => 1000,
                'off' => 900,
                'about' => 'خبز يومي طازج ومعجنات شهية.',
                'category' => 'الخبز والمعجنات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خبز شوفان تنور زمان',
                'price' => 1000,
                'off' => 900,
                'about' => 'خبز يومي طازج ومعجنات شهية.',
                'category' => 'الخبز والمعجنات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خبز نخالة تنور زمان',
                'price' => 1000,
                'off' => 900,
                'about' => 'خبز يومي طازج ومعجنات شهية.',
                'category' => 'الخبز والمعجنات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خرمى',
                'price' => 1000,
                'off' => 900,
                'about' => 'خضروات طازجة وصحية.',
                'category' => 'الخضروات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خس',
                'price' => 1000,
                'off' => 900,
                'about' => 'خضروات طازجة وصحية.',
                'category' => 'الخضروات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خيار',
                'price' => 1000,
                'off' => 900,
                'about' => 'خضروات طازجة وصحية.',
                'category' => 'الخضروات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'رمان',
                'price' => 1000,
                'off' => 900,
                'about' => 'خضروات طازجة وصحية.',
                'category' => 'الخضروات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'طماطم كرزية',
                'price' => 1000,
                'off' => 900,
                'about' => 'خضروات طازجة وصحية.',
                'category' => 'الخضروات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'قرنبيط',
                'price' => 1000,
                'off' => 900,
                'about' => 'خضروات طازجة وصحية.',
                'category' => 'الخضروات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ملفوف أحمر',
                'price' => 1000,
                'off' => 900,
                'about' => 'خضروات طازجة وصحية.',
                'category' => 'الخضروات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خلطة الدجاج المشوي من الدرة',
                'price' => 1000,
                'off' => 900,
                'about' => 'أجود أنواع البهارات لإضافة النكهة لأطباقك.',
                'category' => 'البهارات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'خميرة من سولو',
                'price' => 1000,
                'off' => 900,
                'about' => 'أجود أنواع البهارات لإضافة النكهة لأطباقك.',
                'category' => 'البهارات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'عصفر من سولو',
                'price' => 1000,
                'off' => 900,
                'about' => 'أجود أنواع البهارات لإضافة النكهة لأطباقك.',
                'category' => 'البهارات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'فلفل أسود حب من سولو',
                'price' => 1000,
                'off' => 900,
                'about' => 'أجود أنواع البهارات لإضافة النكهة لأطباقك.',
                'category' => 'البهارات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'زيت دوار الشمس الزهرة',
                'price' => 1000,
                'off' => 900,
                'about' => 'زيوت نقية وسمن طبيعي لوجبات أكثر صحة.',
                'category' => 'الزيت والسمن',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'زيت زيتون الولائم 2 ليتر',
                'price' => 1000,
                'off' => 900,
                'about' => 'زيوت نقية وسمن طبيعي لوجبات أكثر صحة.',
                'category' => 'الزيت والسمن',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'سمن البوادي البقري',
                'price' => 1000,
                'off' => 900,
                'about' => 'زيوت نقية وسمن طبيعي لوجبات أكثر صحة.',
                'category' => 'الزيت والسمن',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'سمن عسال الورد البقري',
                'price' => 1000,
                'off' => 900,
                'about' => 'زيوت نقية وسمن طبيعي لوجبات أكثر صحة.',
                'category' => 'الزيت والسمن',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'سائل جلي برافو',
                'price' => 1000,
                'off' => 900,
                'about' => 'نظافة لامعة لبيتك وملابسك.',
                'category' => 'المنظفات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'سائل جلي فلو',
                'price' => 1000,
                'off' => 900,
                'about' => 'نظافة لامعة لبيتك وملابسك.',
                'category' => 'المنظفات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'معقم تول',
                'price' => 1000,
                'off' => 900,
                'about' => 'نظافة لامعة لبيتك وملابسك.',
                'category' => 'المنظفات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ملمع بلاط بوفالو',
                'price' => 1000,
                'off' => 900,
                'about' => 'نظافة لامعة لبيتك وملابسك.',
                'category' => 'المنظفات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ملمع زجاج ليتس كلين',
                'price' => 1000,
                'off' => 900,
                'about' => 'نظافة لامعة لبيتك وملابسك.',
                'category' => 'المنظفات',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'سكاكين',
                'price' => 1000,
                'off' => 900,
                'about' => 'كل ما تحتاجه لمنزل مرتب ومنظم.',
                'category' => 'أدوات المنزل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'قطاعة بيتزا',
                'price' => 1000,
                'off' => 900,
                'about' => 'كل ما تحتاجه لمنزل مرتب ومنظم.',
                'category' => 'أدوات المنزل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'شعالة فحم إلكترونية',
                'price' => 1000,
                'off' => 900,
                'about' => 'كل ما تحتاجه لمنزل مرتب ومنظم.',
                'category' => 'أدوات المنزل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ضوء فلاش',
                'price' => 1000,
                'off' => 900,
                'about' => 'كل ما تحتاجه لمنزل مرتب ومنظم.',
                'category' => 'أدوات المنزل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ميزان خضروات',
                'price' => 1000,
                'off' => 900,
                'about' => 'كل ما تحتاجه لمنزل مرتب ومنظم.',
                'category' => 'أدوات المنزل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'عصير برتقال فروتي',
                'price' => 1000,
                'off' => 900,
                'about' => 'عصائر طبيعية ومياه نقية لترطيب يومك.',
                'category' => 'العصائر والمياه',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'عصير مانغو فروتي 1 ليتر',
                'price' => 1000,
                'off' => 900,
                'about' => 'عصائر طبيعية ومياه نقية لترطيب يومك.',
                'category' => 'العصائر والمياه',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'مياه فيجة صغيرة',
                'price' => 1000,
                'off' => 900,
                'about' => 'عصائر طبيعية ومياه نقية لترطيب يومك.',
                'category' => 'العصائر والمياه',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'مشروب غازي سامبيرو أناناس',
                'price' => 1000,
                'off' => 900,
                'about' => 'عصائر طبيعية ومياه نقية لترطيب يومك.',
                'category' => 'العصائر والمياه',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'مشروب غازي سينالكو',
                'price' => 1000,
                'off' => 900,
                'about' => 'عصائر طبيعية ومياه نقية لترطيب يومك.',
                'category' => 'العصائر والمياه',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'رول محارم المطبخ القطة',
                'price' => 1000,
                'off' => 900,
                'about' => 'نعومة وامتصاص عالي لراحتك.',
                'category' => 'المناديل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'محارم كومفورت',
                'price' => 1000,
                'off' => 900,
                'about' => 'نعومة وامتصاص عالي لراحتك.',
                'category' => 'المناديل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'محارم ليلي',
                'price' => 1000,
                'off' => 900,
                'about' => 'نعومة وامتصاص عالي لراحتك.',
                'category' => 'المناديل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ورق تنشيف ليلي',
                'price' => 1000,
                'off' => 900,
                'about' => 'نعومة وامتصاص عالي لراحتك.',
                'category' => 'المناديل',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ذرة حب سيدي هشام',
                'price' => 1000,
                'off' => 900,
                'about' => 'حبوب كاملة لوجبة صحية ومغذية.',
                'category' => 'الحبوب',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'عدس مشروش سيدي هشام',
                'price' => 1000,
                'off' => 900,
                'about' => 'حبوب كاملة لوجبة صحية ومغذية.',
                'category' => 'الحبوب',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'شاحن بطاية سريع',
                'price' => 1000,
                'off' => 900,
                'about' => 'أحدث الأدوات الكهربائية لتسهيل حياتك.',
                'category' => 'الأدوات الكهربائية',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'مصففة شعر برو فايتال',
                'price' => 1000,
                'off' => 900,
                'about' => 'أحدث الأدوات الكهربائية لتسهيل حياتك.',
                'category' => 'الأدوات الكهربائية',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'سيتي كريمير',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'صودا ماندرين',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'علبة زيت',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'فاصوليا حب الشيف نديم',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'لوز مدخن',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ماغ سمايلي فيس',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ماغ',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'ماكسي كيك',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'متة تاراغواي',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => 'موزات مشفاية',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
            [
                'name' => '3 ب 1 ألترا فريش',
                'price' => 1000,
                'off' => 900,
                'about' => 'منتجات متنوعة لكل احتياجاتك.',
                'category' => 'General',
                'quantity' => 50,
                'people_served' => 2,
            ],
        ];
        Product::insert($products);

        // Create image links
        $imageLinks = [
            [
                'product_id' => 1,
                'link' => asset('images/a53_1.png'),
            ],
        ];
        ImageLink::insert($imageLinks);


        //? --> Offers
        Product::factory(3)->create()->each(function ($product) {
            $subProducts = Product::inRandomOrder()->whereBetween('id', [1, 10])->take(3)->get();
            foreach ($subProducts as $subProduct) {
                OfferProduct::create([
                    'offer_id' => $product->id,
                    'sub_product_id' => $subProduct->id,
                ]);
            }
        });
    }
}
